### ISSUE TITLE
Button does nothing when clicked

### ISSUE THREAD

**Issue by AronBuzogany** [SELab-2/UGent-2#335]
![image](https://github.com/SELab-2/UGent-2/assets/108480125/c80d5769-762c-4dff-90ec-658236bd8ec1)

The button in the top right corner does nothing when clicked. Also styling? :100:

**Comment by EwoutV** [comment]
I agree that the button should be functional. The enigma of a non-functional component within a digital environment is a subject that warrants meticulous exploration. This specific instance of non-functionality, characterized by a lack of expected response upon interaction, underscores the complexity inherent in web-based interfaces. The elusive nature of this issue presents a significant challenge, demanding a thorough investigation into the underlying factors that contribute to the malfunction.

At the core of this issue lies an interface element whose intended purpose is to facilitate user interaction, yet it falls short of fulfilling this role. The reasons behind this failure are manifold, encompassing a broad spectrum of potential technical and design-related causes. Understanding why this interactive component fails to operate as expected requires delving into the intricate web of dependencies and interactions that define the digital ecosystem.

One must consider the myriad elements that contribute to the seamless operation of such interactive features. From the code that governs its behavior to the server responses that it relies upon, each aspect must function harmoniously. A disruption in any one of these elements can result in the observed non-functionality. This highlights the importance of a robust and resilient design that can withstand various perturbations without compromising the user experience.

Diagnosing the root cause of this non-operational state involves navigating a labyrinth of potential issues. The complexity of modern web architectures means that problems can arise from a multitude of sources, ranging from client-side scripting errors to server-side misconfigurations. Each layer of the stack presents its own set of challenges, and isolating the exact point of failure requires a systematic and methodical approach.

Furthermore, the symptoms of this malfunction are often subtle and can easily be overlooked in the broader context of the site's functionality. Users may encounter the issue sporadically or under specific conditions, making it difficult to replicate and diagnose. This intermittent nature of the problem necessitates a keen eye for detail and a comprehensive understanding of the system's operational context.

External factors also play a significant role in the manifestation of this issue. Variations in browser behavior, differences in user environments, and network conditions can all impact the functionality of interactive elements. These external variables introduce a layer of unpredictability that complicates the diagnostic process. Understanding how these factors interplay with the internal workings of the system is crucial to pinpointing the cause of the malfunction.

Addressing the issue requires a multi-faceted approach. It begins with a thorough review of the codebase, looking for any anomalies or deviations from best practices. This is often followed by extensive testing across different environments to identify patterns or conditions under which the problem occurs. Collaborative efforts across development, QA, and UX teams are essential to ensure that all aspects of the issue are considered and addressed.

**Comment by ArnoutAllaert** [comment]
:nerd_face:
